// This file is generated by Slice Machine. Update with care!

import ContactForm from './ContactForm';
import Image from './Image';
import Quote from './Quote';
import References from './References';
import Text from './Text';

export {
	ContactForm,
	Image,
	Quote,
	References,
	Text,
};

export const components = {
	contact_form: ContactForm,
	image: Image,
	quote: Quote,
	references: References,
	text: Text,
};
