// This file is generated by Slice Machine. Update with care!

import ContactForm from './ContactForm';
import Excerpt from './Excerpt';
import FirstLevelNav from './FirstLevelNav';
import Image from './Image';
import Quote from './Quote';
import References from './References';
import Text from './Text';

export {
	ContactForm,
	Excerpt,
	FirstLevelNav,
	Image,
	Quote,
	References,
	Text,
};

export const components = {
	contact_form: ContactForm,
	excerpt: Excerpt,
	first_level_nav: FirstLevelNav,
	image: Image,
	quote: Quote,
	references: References,
	text: Text,
};
